apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streamer
  template:
    metadata:
      labels:
        app: video-streamer
    spec:
      containers:
      - name: video-streamer
        image: your-dockerhub-username/video-streamer:latest  # Replace with your image
        imagePullPolicy: Always
        env:
        - name: WORKER_SERVICE
          value: "worker-service:6000"
        ports:
        - containerPort: 8080  # Change this to match the port your app uses if it exposes one
        volumeMounts:
        - name: tmp-storage
          mountPath: /tmp  # For temporary segment files
      volumes:
      - name: tmp-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: video-streamer-service
spec:
  selector:
    app: video-streamer
  ports:
  - name: http
    port: 8080           # This is the port you can access on the cluster
    targetPort: 8080     # Match this to the containerPort above
  type: ClusterIP         # Change to LoadBalancer if you want to expose it externally (e.g., via MetalLB)
