apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-node
  template:
    metadata:
      labels:
        app: worker-node
    spec:
      containers:
      - name: worker-node
        image: your-dockerhub-username/worker-node:latest  # Replace with your image
        imagePullPolicy: Always
        ports:
        - containerPort: 6000  # Port used by ZMQ to receive video segments
        volumeMounts:
        - name: tmp-storage
          mountPath: /tmp  # If you're saving or processing files
      volumes:
      - name: tmp-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  selector:
    app: worker-node
  ports:
  - name: zmq
    port: 6000           # External port (change this if needed)
    targetPort: 6000     # Internal container port
  type: ClusterIP        # Or LoadBalancer if exposing outside
