
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: server
    env_file: .env.dev
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/server
      - /server/node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo
    container_name: app-db
    env_file: .env.dev
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "${MONGO_HOST}:${DB_PORT}/${MONGO_DB}?authSource=admin", "--quiet"]
      interval: 90s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    env_file: .env.dev
    ports:
      - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
    depends_on:
      db: 
        condition: service_healthy

volumes:
  db-data:
