version: '3.3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: mongo
    container_name: mongodb_container
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
