services:
  app-server:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        NODE_ENV: ${NODE_ENV}
    container_name: app-server
    restart: always
    command: >
      sh -c "
        npm run prisma:generate && 
        npm run db:push &&
        npm run dev
      "
    env_file: .env.development
    ports:
      - "${MAIN_SERVER_PORT}:${MAIN_SERVER_PORT}"
    volumes:
      - .:/app-server
      - /app-server/node_modules
    depends_on:
      mongo-db:
        condition: service_healthy
      websocket:
        condition: service_healthy

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file: .env.development
    ports:
      - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
    depends_on:
      mongo-db:
        condition: service_healthy

  websocket:
    container_name: websocket
    build:
      context: ./websocket
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${WEBSOCKET_SERVER_PORT}:${WEBSOCKET_SERVER_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEBSOCKET_SERVER_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /websocket/node_modules
      - ./websocket:/websocket

  mongo-db:
    image: mongo
    container_name: mongo-db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    env_file: .env.development
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --port ${DB_PORT} --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo-db-data:/data/db
      - mongo-db-config:/data/configdb

  stream-server:
    build: 
      context: ./stream-server
      dockerfile: Dockerfile
      args:
        AntMediaServer: "ant-media-server.zip"
    container_name: stream-server
    ports:
      - "${STREAM_SERVER_PORT}:${STREAM_SERVER_PORT}"   # WebRTC ingestion + HLS broadcast
    volumes:
      - antmedia-webapps:/usr/local/antmedia/webapps
      # - antmedia-conf:/usr/local/antmedia/conf
      # - antmedia-logs:/usr/local/antmedia/log
      # - antmedia-plugins:/usr/local/antmedia/plugins         # For custom plugins
      - antmedia-data:/usr/local/antmedia/data               # For recording & stream data
      - antmedia-streams:/usr/local/antmedia/streams         # For HLS/DASH streams
    healthcheck:
      test: curl --fail http://${STREAM_SERVER_HOST}:${STREAM_SERVER_PORT} || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    entrypoint: /usr/local/antmedia/start.sh

volumes:
  mongo-db-data:
  mongo-db-config:
  antmedia-webapps:
  # antmedia-conf:
  # antmedia-logs:
  # antmedia-plugins:
  antmedia-data:
  antmedia-streams: